[versions]
alchemist = "25.16.2"
ui = "5.0.0"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-incarnation-protelis = { module = "it.unibo.alchemist:alchemist-incarnation-protelis", version.ref = "alchemist" }
alchemist-swingui = { module = "it.unibo.alchemist:alchemist-swingui", version.ref = "alchemist" }
alchemist-incarnation-scafi = { module = "it.unibo.alchemist:alchemist-incarnation-scafi", version.ref = "alchemist"}
alchemist-incarnation-api = { module = "it.unibo.alchemist:alchemist-incarnation-scafi", version.ref = "alchemist"}
alchemist-ui = { module = "it.unibo.alchemist:alchemist-ui-tooling", version.ref = "alchemist" }
alchemist-geometry = { module = "it.unibo.alchemist:alchemist-maps", version.ref = "alchemist" }
tooling-gui = { module = "org.danilopianini:javalib", version.ref = "ui" }
[bundles]
alchemist = ["alchemist", "alchemist-incarnation-scafi", "alchemist-swingui", "alchemist-ui", "alchemist-geometry", "tooling-gui"]

[plugins]
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:0.4.23"
taskTree = "com.dorongold.task-tree:2.1.0"
